export const articlesInitialState = [
  {
    imageSrc: "https://storage.georgia.travel/images/nature-of-georgia.webp",
    title: "Georgia",
    capital: "Tbilisi",
    description: "3713000",
    id: "1",
    vote: 55,
    deleted: false,
    lang: "en",
  },
  {
    imageSrc:
      "https://www.state.gov/wp-content/uploads/2019/04/Japan-2107x1406.jpg",
    title: "Japan",
    capital: "Tokyo",
    description: "125100000",
    id: "2",
    vote: 23,
    deleted: false,
    lang: "en",
  },
  {
    imageSrc:
      "https://media-magazine.trivago.com/wp-content/uploads/2021/11/07153335/beautiful-places-ireland-skellig-michael.jpg",
    title: "Ireland",
    capital: "Dublin",
    description: "5127000",
    id: "3",
    vote: 30,
    deleted: false,
    lang: "en",
  },
  {
    id: "1",
    title: "საქართველო",
    capital: "თბილისი",
    description: "3713000",
    vote: 55,
    imageSrc: "https://storage.georgia.travel/images/nature-of-georgia.webp",
    deleted: false,
    lang: "ka",
  },
  {
    id: "2",
    title: "იაპონია",
    capital: "ტოკიო",
    description: "125100000",
    imageSrc:
      "https://www.state.gov/wp-content/uploads/2019/04/Japan-2107x1406.jpg",
    vote: 23,
    deleted: false,
    lang: "ka",
  },
  {
    id: "3",
    title: "ირლანდია",
    capital: "დუბლინი",
    description: "5127000",
    vote: 30,
    imageSrc:
      "https://media-magazine.trivago.com/wp-content/uploads/2021/11/07153335/beautiful-places-ireland-skellig-michael.jpg",
    deleted: false,
    lang: "ka",
  },
];

// export const articlesInitialState =  {

//   en: [
//     {
//       imageSrc: "https://storage.georgia.travel/images/nature-of-georgia.webp",
//       title: "Georgia",
//       capital: "Tbilisi",
//       description: "3713000",
//       id: "1",
//       vote: 55,
//       deleted: false,
//     },
//     {
//       imageSrc: "https://www.state.gov/wp-content/uploads/2019/04/Japan-2107x1406.jpg",
//       title: "Japan",
//       capital: "Tokyo",
//       description: "125100000",
//       id: "2",
//       vote: 23,
//       deleted: false,
//     },
//     {
//       imageSrc: "https://media-magazine.trivago.com/wp-content/uploads/2021/11/07153335/beautiful-places-ireland-skellig-michael.jpg",
//       title: "Ireland",
//       capital: "Dublin",
//       description: "5127000",
//       id: "3",
//       vote: 30,
//       deleted: false,
//     },
//   ],
//   ka: [
//     {
//       id: "1",
//       title: "საქართველო",
//       capital: "თბილისი",
//       description: "3713000",
//       vote: 55,
//       imageSrc: "https://storage.georgia.travel/images/nature-of-georgia.webp",
//       deleted: false,
//     },
//     {
//       id: "2",
//       title: "იაპონია",
//       capital: "ტოკიო",
//       description: "125100000",
//       imageSrc: "https://www.state.gov/wp-content/uploads/2019/04/Japan-2107x1406.jpg",
//       vote: 23,
//       deleted: false,
//     },
//     {
//       id: "3",
//       title: "ირლანდია",
//       capital: "დუბლინი",
//       description: "5127000",
//       vote: 30,
//       imageSrc: "https://media-magazine.trivago.com/wp-content/uploads/2021/11/07153335/beautiful-places-ireland-skellig-michael.jpg",
//       deleted: false,
//     },
//   ],
// };
